/**
 * Retire only machine-root rows generated by the former A:–Z: startup scan.
 *
 * The exact `Local Disk X:` display-name signature keeps explicitly named roots
 * and every project registration active. Archiving is reversible and the
 * database layer creates a pre-migration backup when configured.
 */
export const RETIRE_AUTO_MACHINE_ROOTS_MIGRATION_SQL = `
-- Some early legacy databases recorded 001/005 without retaining the workspace
-- table. Recreate the latest shape defensively so this data migration remains
-- backward-compatible instead of failing before unrelated goal migrations load.
CREATE TABLE IF NOT EXISTS workspaces (
  id TEXT PRIMARY KEY NOT NULL,
  display_name TEXT NOT NULL,
  root_path TEXT NOT NULL UNIQUE,
  real_root_path TEXT NOT NULL,
  created_at TEXT NOT NULL,
  archived_at TEXT
);
CREATE INDEX IF NOT EXISTS idx_workspaces_archived_at ON workspaces(archived_at);

UPDATE workspaces
SET archived_at = COALESCE(archived_at, strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
WHERE archived_at IS NULL
  AND length(root_path) IN (2, 3)
  AND substr(root_path, 2, 1) = ':'
  AND (length(root_path) = 2 OR substr(root_path, 3, 1) IN (char(92), '/'))
  AND upper(substr(root_path, 1, 1)) BETWEEN 'A' AND 'Z'
  AND lower(display_name) = 'local disk ' || lower(substr(root_path, 1, 1)) || ':';
`;
