// Generated by apps/desktop/scripts/write-capability-integrity.mjs.
export const WINDOWS_CAPABILITY_BRIDGE_SHA256 = '4cc3e862abad4db7ac396f0969b619070afa92281cf0b10f5adeaae7e4144dba' as const;
export const WINDOWS_CAPABILITY_BRIDGE_SIZE_BYTES = 58353 as const;
