// Generated by apps/desktop/scripts/write-capability-integrity.mjs.
export const WINDOWS_CAPABILITY_BRIDGE_SHA256 = '051da54799cb8155b136724fecb5dbeb87e1d7c6f699ad82fda7f945c2cbd60b' as const;
export const WINDOWS_CAPABILITY_BRIDGE_SIZE_BYTES = 58503 as const;
